name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 零点自动运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate GitHub Contribution Snake
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          snake.svg
          snake-dark.svg?palette=github-dark

    - name: Commit and push snake.svg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add *.svg
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update contribution snake"
          git push
        fi
